import {
	type ProviderName,
	type ModelInfo,
	aiCoderModels,
	aliyunModels,
	anthropicModels,
	bedrockModels,
	cerebrasModels,
	claudeCodeModels,
	deepSeekModels,
	moonshotModels,
	geminiModels,
	mistralModels,
	openAiNativeModels,
	qwenCodeModels,
	vertexModels,
	xaiModels,
	groqModels,
	sambaNovaModels,
	doubaoModels,
	internationalZAiModels,
	fireworksModels,
	featherlessModels,
	minimaxModels,
	basetenModels,
	iFlowModels,
	infiniModels,
	modelScopeModels,
	qianfanModels,
	zenModels,
	zCodeModels,
} from "@roo-code/types"

export const MODELS_BY_PROVIDER: Partial<Record<ProviderName, Record<string, ModelInfo>>> = {
	aicoder: aiCoderModels,
	aliyun: aliyunModels,
	anthropic: anthropicModels,
	"claude-code": claudeCodeModels,
	bedrock: bedrockModels,
	cerebras: cerebrasModels,
	deepseek: deepSeekModels,
	doubao: doubaoModels,
	iflow: iFlowModels,
	infini: infiniModels,
	moonshot: moonshotModels,
	gemini: geminiModels,
	mistral: mistralModels,
	"openai-native": openAiNativeModels,
	"qwen-code": qwenCodeModels,
	qianfan: qianfanModels,
	vertex: vertexModels,
	xai: xaiModels,
	groq: groqModels,
	sambanova: sambaNovaModels,
	zai: internationalZAiModels,
	zcode: zCodeModels,
	modelscope: modelScopeModels,
	zen: zenModels,
	fireworks: fireworksModels,
	featherless: featherlessModels,
	minimax: minimaxModels,
	baseten: basetenModels,
}

export const PROVIDERS = [
	{ value: "aicoder", label: "AiCoder" },
	{ value: "aliyun", label: "Aliyun" },
	{ value: "openrouter", label: "OpenRouter" },
	// { value: "deepinfra", label: "DeepInfra" },
	// { value: "anthropic", label: "Anthropic" },
	// { value: "claude-code", label: "Claude Code" },
	// { value: "cerebras", label: "Cerebras" },
	// { value: "gemini", label: "Google Gemini" },
	// { value: "doubao", label: "Doubao" },
	// { value: "deepseek", label: "DeepSeek" },
	{ value: "iflow", label: "iFlow" },
	{ value: "infini", label: "Infini" },
	// { value: "moonshot", label: "Moonshot" },
	// { value: "openai-native", label: "OpenAI" },
	{ value: "openai", label: "OpenAI Compatible" },
	// { value: "qwen-code", label: "Qwen Code" },
	{ value: "qianfan", label: "Qianfan" },
	// { value: "vertex", label: "GCP Vertex AI" },
	// { value: "bedrock", label: "Amazon Bedrock" },
	// { value: "vscode-lm", label: "VS Code LM API" },
	// { value: "mistral", label: "Mistral" },
	// { value: "lmstudio", label: "LM Studio" },
	// { value: "ollama", label: "Ollama" },
	// { value: "unbound", label: "Unbound" },
	// { value: "requesty", label: "Requesty" },
	// { value: "xai", label: "xAI (Grok)" },
	// { value: "groq", label: "Groq" },
	// { value: "huggingface", label: "Hugging Face" },
	// { value: "chutes", label: "Chutes AI" },
	// { value: "litellm", label: "LiteLLM" },
	// { value: "sambanova", label: "SambaNova" },
	// { value: "zai", label: "Z.ai" },
	{ value: "zcode", label: "ZCode" },
	{ value: "modelscope", label: "ModelScope" },
	{ value: "zen", label: "Zen" },
	// { value: "fireworks", label: "Fireworks AI" },
	// { value: "featherless", label: "Featherless AI" },
	// { value: "io-intelligence", label: "IO Intelligence" },
	// { value: "roo", label: "Roo Code Cloud" },
	// { value: "vercel-ai-gateway", label: "Vercel AI Gateway" },
	// { value: "minimax", label: "MiniMax" },
	// { value: "baseten", label: "Baseten" },
].sort((a, b) => a.label.localeCompare(b.label))
